wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True]'
_last_obs:
  desc: null
  value: "[[ 1.3657334  -3.8601196  16.508793    1.7590306  -2.8104239  17.326101\n\
    \   0.          0.          0.        ]\n [ 1.4940449  -1.2484431  15.858203 \
    \   1.8277239  -0.4566052  16.247524\n   0.          0.          0.        ]\n\
    \ [ 1.5363696  -7.4782267  11.239828    1.489232   -7.720543   10.167679\n   0.\
    \          0.          0.        ]\n [ 1.8358146  -7.292145    6.3492103   1.726775\
    \   -7.571164    7.4056745\n   0.          0.          0.        ]\n [ 0.87613636\
    \  0.62911564 18.5118      1.4658074   2.034265   18.50873\n   0.          0.\
    \          0.        ]\n [ 7.208774    4.6193185  16.832962    7.211618    5.3291173\
    \  16.417784\n   0.          0.          0.        ]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fede6ed1220>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 10000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    session_history: code/_session_history.ipynb
    start_time: 1677765527.77228
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 13
      - 15
      - 16
      - 22
      - 23
      - 35
      4: 3.8.12
      5: 0.13.10
      8:
      - 1
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-1. -1. -1. -1. -1.], [1. 1. 1. 1. 1.], (5,), float32)
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=9,\
    \ out_features=32, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=64,\
    \ out_features=5, bias=True)\n  (log_std): Linear(in_features=64, out_features=5,\
    \ bias=True)\n)"
algo:
  desc: null
  value: SAC
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: auto
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: False\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fede6ed17f0>
env_id:
  desc: null
  value: darm/DarmHand-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
eval_freq:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 40000
log_ent_coef:
  desc: null
  value: tensor([0.], requires_grad=True)
log_interval:
  desc: null
  value: 20
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fee3030a700>
max_no_improvement_evals:
  desc: null
  value: 10
mean_reward_thresh:
  desc: null
  value: 1300
n_envs:
  desc: null
  value: 6
no_improvement_min_evals:
  desc: null
  value: 20
num_cpu:
  desc: null
  value: 6
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf], [inf inf inf inf inf
    inf inf inf inf], (9,), float32)
optimize_memory_usage:
  desc: null
  value: 'False'
pi_net_arch:
  desc: null
  value:
  - 32
  - 256
  - 256
  - 64
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=9, out_features=32, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=32, out_features=256, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=256, out_features=256, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=256, out_features=64, bias=True)\n      (7): ReLU()\n\
    \    )\n    (mu): Linear(in_features=64, out_features=5, bias=True)\n    (log_std):\
    \ Linear(in_features=64, out_features=5, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=14,\
    \ out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=64, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=64,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': {''pi'': [32, 256, 256, 64], ''qf'': [32, 256, 256, 64]},
    ''use_sde'': False}'
qf_net_arch:
  desc: null
  value:
  - 32
  - 256
  - 256
  - 64
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7fede505c2b0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
rl_lib:
  desc: null
  value: SB3
run_local_dir:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/darm_sf_hand/test1_SF_SB3_SAC_4
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_finger_env:
  desc: null
  value: true
start_time:
  desc: null
  value: 1677765542522863946
target_entropy:
  desc: null
  value: '-5.0'
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
tensorboard_log:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/darm_sf_hand/test1_SF_SB3_SAC_4
total_timesteps:
  desc: null
  value: 10000000
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
wandb_model_save_freq:
  desc: null
  value: 2000
