wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1677685867.083495
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 15
      - 16
      - 22
      - 23
      - 35
      4: 3.8.12
      5: 0.13.10
      8:
      - 1
      - 5
algo:
  desc: null
  value: SAC
env_id:
  desc: null
  value: darm/DarmHand-v0
eval_freq:
  desc: null
  value: 2000
learning_starts:
  desc: null
  value: 40000
log_interval:
  desc: null
  value: 20
max_no_improvement_evals:
  desc: null
  value: 10
mean_reward_thresh:
  desc: null
  value: 1300
no_improvement_min_evals:
  desc: null
  value: 20
num_cpu:
  desc: null
  value: 6
pi_net_arch:
  desc: null
  value:
  - 128
  - 256
  - 256
  - 128
qf_net_arch:
  desc: null
  value:
  - 128
  - 256
  - 256
  - 128
rl_lib:
  desc: null
  value: SB3
seed:
  desc: null
  value: 0
single_finger_env:
  desc: null
  value: false
total_timesteps:
  desc: null
  value: 10000000
wandb_model_save_freq:
  desc: null
  value: 2000
