wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True]'
_last_obs:
  desc: null
  value: "[[ 1.80463994e+00 -5.53337336e+00  9.13729191e+00 -7.49114975e-02\n   9.93370473e-01\
    \ -8.71966332e-02 -2.85489921e-04  2.93000007e+00\n   8.70000005e-01  9.07999992e+00\
    \  2.19843602e+00 -2.93757224e+00\n   1.20433779e+01  1.73435950e+00 -5.57622337e+00\
    \  1.21108551e+01\n   1.75965834e+00 -5.69145584e+00  1.00041561e+01  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00  0.00000000e+00]\n [ 3.73227048e+00 -1.78563905e+00\
    \  1.46302061e+01  6.18226469e-01\n   7.73162127e-01  1.87271414e-03 -1.41466931e-01\
    \  2.93000007e+00\n   8.70000005e-01  9.07999992e+00  4.02198887e+00  1.97902822e+00\n\
    \   1.37051506e+01  3.81179690e+00 -4.35418844e-01  1.48491192e+01\n   3.34086585e+00\
    \ -2.39465594e+00  1.42232485e+01  0.00000000e+00\n   0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00]\n [ 1.46233606e+00  1.99860179e+00  1.70186405e+01  8.62623632e-01\n\
    \   4.88305539e-01 -1.30063906e-01 -2.28385981e-02  2.93000007e+00\n   8.70000005e-01\
    \  9.07999992e+00  2.32147217e+00  2.04288268e+00\n   1.37777061e+01  2.01469135e+00\
    \  2.81390548e+00  1.63260021e+01\n   1.57291353e+00  8.31604004e-01  1.68982010e+01\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]\n [ 1.59672785e+00\
    \ -7.98743200e+00  7.71300888e+00  4.75135058e-01\n   8.72774303e-01 -1.09436832e-01\
    \  2.31361929e-02  2.93000007e+00\n   8.70000005e-01  9.07999992e+00  2.02323365e+00\
    \ -3.90455222e+00\n   9.52252197e+00  1.92994428e+00 -6.09274626e+00  7.97801447e+00\n\
    \   1.96205688e+00 -7.54263067e+00  6.44540119e+00  0.00000000e+00\n   0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00]\n [ 4.09346104e+00  6.44031048e-01  1.85378666e+01\
    \  9.91281271e-01\n   7.64024407e-02  5.56333438e-02 -9.18100178e-02  2.93000007e+00\n\
    \   8.70000005e-01  9.07999992e+00  3.57154703e+00  2.07516909e+00\n   1.37651234e+01\
    \  3.73064566e+00  1.61362731e+00  1.64002838e+01\n   3.90267897e+00  1.50136447e+00\
    \  1.85002594e+01  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]\n\
    \ [ 3.40067887e+00 -1.31109989e+00  1.83875580e+01  9.80998039e-01\n   1.67252153e-01\
    \  3.00530829e-02 -9.36287940e-02  2.93000007e+00\n   8.70000005e-01  9.07999992e+00\
    \  3.21984673e+00  9.55234051e-01\n   1.39506388e+01  3.26573896e+00  3.78813982e-01\
    \  1.65675144e+01\n   3.34927320e+00  1.81137502e-01  1.86665726e+01  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00  0.00000000e+00]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fe670db4460>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 10000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    session_history: code/_session_history.ipynb
    start_time: 1680617762.88922
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 13
      - 15
      - 16
      - 22
      - 23
      - 35
      4: 3.8.12
      5: 0.13.10
      8:
      - 1
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-1. -1. -1. -1. -1.], [1. 1. 1. 1. 1.], (5,), float32)
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=28,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (5): ReLU()\n  )\n  (mu): Linear(in_features=128,\
    \ out_features=5, bias=True)\n  (log_std): Linear(in_features=128, out_features=5,\
    \ bias=True)\n)"
algo:
  desc: null
  value: SAC
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: auto
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: False\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fe6715c77f0>
env_id:
  desc: null
  value: darm/DarmHand-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
eval_freq:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 40000
log_ent_coef:
  desc: null
  value: tensor([0.], requires_grad=True)
log_interval:
  desc: null
  value: 20
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fe672121d30>
max_no_improvement_evals:
  desc: null
  value: 10
mean_reward_thresh:
  desc: null
  value: 1300
n_envs:
  desc: null
  value: 6
no_improvement_min_evals:
  desc: null
  value: 20
num_cpu:
  desc: null
  value: 6
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf], [inf\
    \ inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf\n inf inf\
    \ inf inf inf inf inf inf inf inf], (28,), float32)"
optimize_memory_usage:
  desc: null
  value: 'False'
pi_net_arch:
  desc: null
  value:
  - 128
  - 128
  - 128
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=28, out_features=128, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=128, out_features=128, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=128, out_features=128, bias=True)\n      (5): ReLU()\n\
    \    )\n    (mu): Linear(in_features=128, out_features=5, bias=True)\n    (log_std):\
    \ Linear(in_features=128, out_features=5, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=33,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=128,\
    \ out_features=128, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': {''pi'': [128, 128, 128], ''qf'': [128, 128, 128]}, ''use_sde'':
    False}'
qf_net_arch:
  desc: null
  value:
  - 128
  - 128
  - 128
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7fe6b0b77fd0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
rl_lib:
  desc: null
  value: SB3
run_local_dir:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/dii/SB3_SAC_dii_torque
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
start_time:
  desc: null
  value: 1680617799569652726
target_entropy:
  desc: null
  value: '-5.0'
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
tensorboard_log:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/dii/SB3_SAC_dii_torque
total_timesteps:
  desc: null
  value: 10000000
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
wandb_model_save_freq:
  desc: null
  value: 2000
