wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True]'
_last_obs:
  desc: null
  value: "[[ 9.50238407e-01 -5.41494703e+00  1.08755198e+01  2.06949878e+00\n   2.12209940e+00\
    \  1.60709858e+01  1.25565910e+00 -7.98069239e+00\n   1.50730543e+01 -1.33420363e-01\
    \ -8.03996849e+00  8.10750294e+00\n  -3.35334659e+00 -6.27635956e+00  1.09694920e+01\
    \ -1.47851231e-02\n  -5.04765081e+00  1.04704475e+01  2.16900349e+00  1.08603120e+00\n\
    \   1.58432999e+01  1.02473378e+00 -8.44392967e+00  1.43443565e+01\n  -3.44393790e-01\
    \ -8.12071133e+00  9.18649101e+00 -3.40759206e+00\n  -6.58747530e+00  1.00192032e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [ 1.92079198e+00 -5.06983852e+00  1.23453646e+01  3.78782487e+00\n  -3.53126717e+00\
    \  1.67716904e+01  3.41663289e+00  2.46753454e+00\n   1.94454403e+01 -2.33381435e-01\
    \ -5.34250116e+00  1.27772951e+01\n  -3.61812615e+00 -3.12153387e+00  1.46438808e+01\
    \  1.02375865e+00\n  -5.43441105e+00  1.18939056e+01  4.23776913e+00 -2.90225673e+00\n\
    \   1.69799080e+01  3.80290556e+00  1.06124377e+00  1.94670238e+01\n  -3.96750927e-01\
    \ -5.50791454e+00  1.18570566e+01 -3.06757188e+00\n  -4.28829002e+00  1.37606592e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [ 1.41410744e+00 -3.86503601e+00  1.20590792e+01  1.13862860e+00\n   2.07922220e+00\
    \  1.73214626e+01 -6.97101712e-01  1.14875567e+00\n   1.83482113e+01 -2.40224540e-01\
    \ -5.23282194e+00  7.12207556e+00\n  -5.63202763e+00  3.34140015e+00  1.51096764e+01\
    \  2.07942319e+00\n  -3.48159814e+00  1.24786978e+01  1.23878062e+00  9.71728504e-01\n\
    \   1.73966846e+01 -3.63233894e-01 -1.07387416e-02  1.82582378e+01\n  -2.72144735e-01\
    \ -5.83655024e+00  7.84014225e+00 -5.28486490e+00\n   4.33241701e+00  1.48601551e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [-1.69635427e+00 -3.99270868e+00  8.47471142e+00  4.04380274e+00\n  -6.01634169e+00\
    \  1.52851095e+01  3.93352807e-01 -2.99192572e+00\n   1.57953558e+01 -5.11833668e-01\
    \ -7.32657957e+00  8.20104313e+00\n  -5.81704903e+00  2.84890795e+00  1.58241196e+01\
    \ -1.92430246e+00\n  -3.91160893e+00  7.62071466e+00  3.78347421e+00 -6.70543575e+00\n\
    \   1.43722334e+01  8.31717774e-02 -2.08559346e+00  1.66149712e+01\n  -2.52395391e-01\
    \ -7.65740633e+00  9.36349010e+00 -6.15222025e+00\n   2.03139353e+00  1.59285822e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [-2.61150885e+00 -6.21056318e+00  7.44261360e+00  3.20683122e+00\n  -4.93019629e+00\
    \  1.60732670e+01  1.52792311e+00 -7.47866297e+00\n   1.44676151e+01 -3.14949930e-01\
    \ -7.24986553e+00  8.58091831e+00\n  -2.98976564e+00 -5.00122881e+00  1.05569763e+01\
    \ -2.21855283e+00\n  -6.31829548e+00  8.33924961e+00  3.23482847e+00 -5.56028414e+00\n\
    \   1.55648899e+01  1.27808297e+00 -7.87791681e+00  1.38043947e+01\n  -4.99373347e-01\
    \ -7.36139488e+00  9.55271912e+00 -2.62284327e+00\n  -5.31729794e+00  9.67123699e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [ 3.95346045e+00 -2.88517594e+00  1.32786694e+01  2.89752674e+00\n  -4.63768196e+00\
    \  1.48782921e+01  6.89931989e-01 -9.25498009e+00\n   1.03464165e+01 -2.27695704e+00\
    \ -4.17024493e-01  1.68352795e+01\n  -5.68383169e+00 -5.31948662e+00  1.37889242e+01\
    \  2.95539427e+00\n  -3.29902244e+00  1.31560755e+01  2.49468780e+00 -5.20592117e+00\n\
    \   1.41320734e+01  5.22272766e-01 -9.10249138e+00  1.11496353e+01\n  -1.87950754e+00\
    \ -1.39277518e+00  1.66224747e+01 -5.67974806e+00\n  -5.70898008e+00  1.30239658e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f7e294c78e0>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 10000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1677765218.764464
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 15
      - 16
      - 22
      - 23
      - 35
      4: 3.8.12
      5: 0.13.10
      8:
      - 1
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: "Box([-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.\
    \ -1.\n -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1.], (30,),\
    \ float32)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=45,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=128,\
    \ out_features=30, bias=True)\n  (log_std): Linear(in_features=128, out_features=30,\
    \ bias=True)\n)"
algo:
  desc: null
  value: SAC
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: auto
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: False\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f7e2bbdd580>
env_id:
  desc: null
  value: darm/DarmHand-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
eval_freq:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 40000
log_ent_coef:
  desc: null
  value: tensor([0.], requires_grad=True)
log_interval:
  desc: null
  value: 20
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f7e2bbde3a0>
max_no_improvement_evals:
  desc: null
  value: 10
mean_reward_thresh:
  desc: null
  value: 1300
n_envs:
  desc: null
  value: 6
no_improvement_min_evals:
  desc: null
  value: 20
num_cpu:
  desc: null
  value: 6
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf\
    \ -inf], [inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf\
    \ inf\n inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf\n\
    \ inf inf inf inf inf inf inf inf inf], (45,), float32)"
optimize_memory_usage:
  desc: null
  value: 'False'
pi_net_arch:
  desc: null
  value:
  - 128
  - 256
  - 256
  - 128
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=45, out_features=128, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=128, out_features=256, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=256, out_features=256, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=256, out_features=128, bias=True)\n      (7): ReLU()\n\
    \    )\n    (mu): Linear(in_features=128, out_features=30, bias=True)\n    (log_std):\
    \ Linear(in_features=128, out_features=30, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': {''pi'': [128, 256, 256, 128], ''qf'': [128, 256, 256, 128]},
    ''use_sde'': False}'
qf_net_arch:
  desc: null
  value:
  - 128
  - 256
  - 256
  - 128
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7f7e2bbdd370>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
rl_lib:
  desc: null
  value: SB3
run_local_dir:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/darm_mf_hand/test1_MF_SB3_SAC
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_finger_env:
  desc: null
  value: false
start_time:
  desc: null
  value: 1677765237092032248
target_entropy:
  desc: null
  value: '-30.0'
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
tensorboard_log:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/darm_mf_hand/test1_MF_SB3_SAC
total_timesteps:
  desc: null
  value: 10000000
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
wandb_model_save_freq:
  desc: null
  value: 2000
