wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True]'
_last_obs:
  desc: null
  value: "[[ 6.06554794e+00 -1.68613279e+00  1.22869873e+01  1.13312232e+00\n  -5.09413910e+00\
    \  1.34452877e+01 -2.17337417e-03  5.55558026e-01\n   1.73372097e+01 -8.55386972e-01\
    \ -6.97802305e+00  1.09805460e+01\n  -4.31926203e+00 -5.01130390e+00  1.18296614e+01\
    \  6.89718723e+00\n  -1.75987387e+00  1.16132612e+01  1.37700486e+00 -5.46926117e+00\n\
    \   1.23377638e+01 -2.87182450e-01  1.62579632e+00  1.73475380e+01\n  -5.81056893e-01\
    \ -6.84497881e+00  9.83847713e+00 -4.73955822e+00\n  -4.20313263e+00  1.25937824e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [-1.86006439e+00 -3.86556959e+00  9.06824970e+00  3.08253312e+00\n  -5.23598862e+00\
    \  1.34441719e+01  1.83994985e+00 -3.43339944e+00\n   1.48173895e+01 -2.94322163e-01\
    \ -3.79096913e+00  1.39130774e+01\n  -6.01631594e+00  5.09875774e+00  1.46538954e+01\
    \ -1.35175264e+00\n  -4.32029200e+00  9.73290253e+00  2.64285302e+00 -5.54702806e+00\n\
    \   1.25532923e+01  2.22416186e+00 -2.78654790e+00  1.56483688e+01\n  -7.71436691e-02\
    \ -3.25593281e+00  1.46826220e+01 -6.55083227e+00\n   5.94772291e+00  1.37921495e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [ 4.73272181e+00 -6.45187998e+00  1.18447313e+01  2.52513909e+00\n  -6.61818790e+00\
    \  1.44821053e+01 -1.87632322e-01  2.05688000e+00\n   1.92819443e+01 -2.24430466e+00\
    \ -1.96692908e+00  1.86111946e+01\n  -3.78928423e+00  7.90645242e-01  1.50530796e+01\
    \  5.86179876e+00\n  -6.57010460e+00  1.14091158e+01  2.50709343e+00 -6.14689684e+00\n\
    \   1.51444178e+01  1.59366697e-01  1.23203397e+00  1.93251572e+01\n  -2.76552510e+00\
    \ -4.71221894e-01  1.88311653e+01 -4.41231966e+00\n   1.98706794e+00  1.48818350e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [ 2.92002773e+00 -3.28521109e+00  1.28250465e+01  4.19389677e+00\n   1.81878686e+00\
    \  1.74553890e+01  2.39044023e+00 -3.75462532e+00\n   1.52192211e+01 -2.26873875e+00\
    \ -3.57550502e+00  1.48272276e+01\n  -6.87470961e+00  1.53968430e+00  1.46452980e+01\
    \  4.02201939e+00\n  -3.30788064e+00  1.29412966e+01  3.66197348e+00  5.80457985e-01\n\
    \   1.73351803e+01  2.33457541e+00 -3.02206230e+00  1.59264507e+01\n  -2.24582481e+00\
    \ -2.72841740e+00  1.53589735e+01 -6.33180857e+00\n   5.81300080e-01  1.50080605e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [-5.96783042e-01 -4.77454185e+00  1.16168480e+01  2.87652373e+00\n  -6.49548578e+00\
    \  1.50630293e+01 -8.31092775e-01  4.43207562e-01\n   1.83996086e+01 -2.60770178e+00\
    \ -5.97803593e+00  1.58895979e+01\n  -2.16133904e+00 -7.54427433e+00  8.41477585e+00\
    \ -1.33389521e+00\n  -4.46222258e+00  1.11271324e+01  2.65353799e+00 -7.21756077e+00\n\
    \   1.38066492e+01 -1.12180328e+00 -2.85202533e-01  1.82228470e+01\n  -1.99767637e+00\
    \ -6.80627584e+00  1.48666496e+01 -3.00644970e+00\n  -7.34245586e+00  9.46771717e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]\n\
    \ [ 2.58060861e+00 -6.35049343e+00  1.17724276e+01  3.49080086e+00\n  -3.62787223e+00\
    \  1.76209240e+01  1.17266215e-01 -6.10223341e+00\n   1.22693119e+01 -3.84648609e+00\
    \ -1.16081929e+00  1.55730906e+01\n  -3.80104637e+00 -4.31338501e+00  1.06060810e+01\
    \  3.51666141e+00\n  -5.89170885e+00  1.20717325e+01  3.02514625e+00 -4.27738667e+00\n\
    \   1.72637215e+01 -2.91256517e-01 -5.90760136e+00  1.33517933e+01\n  -3.42630887e+00\
    \ -2.08144903e+00  1.54166727e+01 -3.97952628e+00\n  -3.78210711e+00  1.14101086e+01\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f21d0765970>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 10000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    session_history: code/_session_history.ipynb
    start_time: 1677765842.322102
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 22
      - 23
      - 35
      4: 3.8.12
      5: 0.13.10
      8:
      - 1
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: "Box([-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.\
    \ -1.\n -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1.], (30,),\
    \ float32)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=45,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=128,\
    \ out_features=30, bias=True)\n  (log_std): Linear(in_features=128, out_features=30,\
    \ bias=True)\n)"
algo:
  desc: null
  value: SAC
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: auto
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: False\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f21863c1f70>
env_id:
  desc: null
  value: darm/DarmHand-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
eval_freq:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 40000
log_ent_coef:
  desc: null
  value: tensor([0.], requires_grad=True)
log_interval:
  desc: null
  value: 20
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f21863c50d0>
max_no_improvement_evals:
  desc: null
  value: 10
mean_reward_thresh:
  desc: null
  value: 1300
n_envs:
  desc: null
  value: 6
no_improvement_min_evals:
  desc: null
  value: 20
num_cpu:
  desc: null
  value: 6
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf\
    \ -inf], [inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf\
    \ inf\n inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf\n\
    \ inf inf inf inf inf inf inf inf inf], (45,), float32)"
optimize_memory_usage:
  desc: null
  value: 'False'
pi_net_arch:
  desc: null
  value:
  - 128
  - 256
  - 256
  - 128
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=45, out_features=128, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=128, out_features=256, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=256, out_features=256, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=256, out_features=128, bias=True)\n      (7): ReLU()\n\
    \    )\n    (mu): Linear(in_features=128, out_features=30, bias=True)\n    (log_std):\
    \ Linear(in_features=128, out_features=30, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=75,\
    \ out_features=128, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=128,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': {''pi'': [128, 256, 256, 128], ''qf'': [128, 256, 256, 128]},
    ''use_sde'': False}'
qf_net_arch:
  desc: null
  value:
  - 128
  - 256
  - 256
  - 128
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7f21863c1e50>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
rl_lib:
  desc: null
  value: SB3
run_local_dir:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/darm_mf_hand/test1_MF_SB3_SAC
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_finger_env:
  desc: null
  value: false
start_time:
  desc: null
  value: 1677765860929914615
target_entropy:
  desc: null
  value: '-30.0'
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
tensorboard_log:
  desc: null
  value: /home/daniel/DARM/darm_mujoco/darm_training/results/darm_mf_hand/test1_MF_SB3_SAC
total_timesteps:
  desc: null
  value: 10000000
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
wandb_model_save_freq:
  desc: null
  value: 2000
