<?xml version="1.0" encoding="UTF-8"?>
<worldbody xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:include filename="phalanges.xml.xacro" />

    <!-- Single Finger -->
    <xacro:arg name="no_wrist" default="false" />
    <xacro:arg name="digit_i" default="true" />
    <xacro:arg name="digit_ii" default="true" />
    <xacro:arg name="digit_iii" default="true" />
    <xacro:arg name="digit_iv" default="true" />
    <xacro:arg name="digit_v" default="true" />

    <!-- Wrist -->
    <xacro:property name="rc_joint_tf" value="${[0, 0, 0.032]}" />
    <xacro:property name="rc_joint_radius" value="0.012" />
    <xacro:property name="rc_joint_length" value="0.0235" />
    
    <!-- Digit I -->
    <xacro:property name="cm_i_translation" value="${[0.0223607, -0.0073321, 0.0254833]}" />
    <xacro:property name="cm_i_rotation" value="24 -15 -75" />
    <xacro:property name="cm_i_centre_block_offset" value="${[0, 0, 0.013]}" />
    <xacro:property name="metacarpal_i_length" value="0.0395" />
    
    <xacro:property name="pp_i_length" value="0.0335" />
    <!-- <xacro:property name="dp_i_length" value="0.0294" /> -->
    <xacro:property name="dp_i_length" value="0.027" />
    <xacro:property name="proximal_cm_i_radius" value="0.0085" />
    <xacro:property name="distal_cm_i_radius" value="0.0075" />
    <xacro:property name="mcp_i_radius" value="0.0075" />
    <xacro:property name="ip_i_radius" value="0.0065" />

    <!-- Digit II -->
    <xacro:property name="mcp_ii_translation" value="0.0293 0.0087 0.0908" />
    <xacro:property name="mcp_ii_rotation" value="0 5 -10" />
    <xacro:property name="pp_ii_length" value="0.0488" />
    <xacro:property name="mp_ii_length" value="0.0268" />
    <xacro:property name="dp_ii_length" value="0.0211" />

    <xacro:property name="mcp_ii_radius" value="0.0110" />
    <xacro:property name="pip_ii_radius" value="0.0065" />
    <xacro:property name="dip_ii_radius" value="0.0055" />
    <xacro:property name="dorsal_interossei_ii_insertion_tf" value="0.007 -0.007 0.012" />
    <xacro:property name="palmar_interossei_ii_insertion_tf" value="-0.007 -0.007 0.012" />
    <xacro:property name="pp_ii_extensor_communis_insertion_tf" value="0 0.009 0.012" />
    <xacro:property name="flexor_superficialis_ii_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_ii_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_ii_insertion_tf" value="0 -0.004 0.007" />
    <xacro:property name="dp_ii_extensor_hood_insertion_tf" value="0 0.004 0.007" />
    
    <!-- Digit III -->
    <xacro:property name="mcp_iii_translation" value="0.0082 0.0087 0.0933" />
    <xacro:property name="mcp_iii_rotation" value="0 0 0" />
    <xacro:property name="pp_iii_length" value="0.0520" />
    <xacro:property name="mp_iii_length" value="0.0335" />
    <xacro:property name="dp_iii_length" value="0.0204" />

    <xacro:property name="mcp_iii_radius" value="0.0110" />
    <xacro:property name="pip_iii_radius" value="0.0070" />
    <xacro:property name="dip_iii_radius" value="0.0060" />
    <xacro:property name="dorsal_interossei_iii_insertion_tf" value="0.007 -0.007 0.012" />
    <xacro:property name="palmar_interossei_iii_insertion_tf" value="-0.007 -0.007 0.012" />
    <xacro:property name="pp_iii_extensor_communis_insertion_tf" value="0 0.009 0.012" />
    <xacro:property name="flexor_superficialis_iii_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_iii_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_iii_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="dp_iii_extensor_hood_insertion_tf" value="0 0.005 0.007" />

    <!-- Digit IV -->
    <xacro:property name="mcp_iv_translation" value="-0.0103 0.0021 0.0889" />
    <xacro:property name="mcp_iv_rotation" value="0 -5 5" />
    <xacro:property name="pp_iv_length" value="0.0487" />
    <xacro:property name="mp_iv_length" value="0.0330" />
    <xacro:property name="dp_iv_length" value="0.0202" />

    <xacro:property name="mcp_iv_radius" value="0.0095" />
    <xacro:property name="pip_iv_radius" value="0.0065" />
    <xacro:property name="dip_iv_radius" value="0.0055" />
    <xacro:property name="dorsal_interossei_iv_insertion_tf" value="0.007 -0.007 0.012" />
    <xacro:property name="palmar_interossei_iv_insertion_tf" value="-0.007 -0.007 0.012" />
    <xacro:property name="pp_iv_extensor_communis_insertion_tf" value="0 0.007 0.012" />
    <xacro:property name="flexor_superficialis_iv_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_iv_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_iv_insertion_tf" value="0 -0.004 0.007" />
    <xacro:property name="dp_iv_extensor_hood_insertion_tf" value="0 0.004 0.007" />

    <!-- Digit V -->
    <xacro:property name="cm_v_translation" value="-0.0171 0.0038 0.0360" />
    <xacro:property name="cm_v_rotation" value="0 -12 5" />
    <xacro:property name="cm_v_centre_block_offset" value="0 0 0.014" />
    <xacro:property name="metacarpal_v_length" value="0.0349" />
    
    <xacro:property name="mcp_v_translation" value="0 0 0" />
    <xacro:property name="mcp_v_rotation" value="0 0 0" />
    <xacro:property name="pp_v_length" value="0.0416" />
    <xacro:property name="mp_v_length" value="0.0247" />
    <xacro:property name="dp_v_length" value="0.0185" />

    <xacro:property name="proximal_cm_v_radius" value="0.007" />
    <xacro:property name="distal_cm_v_radius" value="0.007" />
    <xacro:property name="mcp_v_radius" value="0.0095" />
    <xacro:property name="pip_v_radius" value="0.0060" />
    <xacro:property name="dip_v_radius" value="0.0050" />
    <xacro:property name="dorsal_interossei_v_insertion_tf" value="0.0055 -0.006 0.012" />
    <xacro:property name="palmar_interossei_v_insertion_tf" value="-0.0055 -0.006 0.012" />
    <xacro:property name="pp_v_extensor_communis_insertion_tf" value="0 0.0075 0.012" />
    <xacro:property name="flexor_superficialis_v_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_v_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_v_insertion_tf" value="0 -0.004 0.007" />
    <xacro:property name="dp_v_extensor_hood_insertion_tf" value="0 0.004 0.007" />
    
    <!-- Tendons -->
    <xacro:property name="tunnel_site_size" value="0.0015" />
    <xacro:property name="tunnel_site_rgba" value="0.5 0.5 0.5 1" />
    <xacro:property name="origin_site_size" value="0.0015" />
    <xacro:property name="origin_site_rgba" value="1 0.5 0.5 1" />
    <xacro:property name="sidesite_size" value="0.001" />
    <xacro:property name="sidesite_rgba" value="1 1 1 0.2" />
    <xacro:property name="wrap_rgba" value="0 0 1 0.2" />
    
    <xacro:property name="extensor_communis_ii_metacarpals_tunnel_tf" value="0.021 0.013 0.051" />
    <xacro:property name="extensor_communis_iii_metacarpals_tunnel_tf" value="0.007 0.013 0.051" />
    <xacro:property name="extensor_communis_iv_metacarpals_tunnel_tf" value="-0.007 0.010 0.051" />

    <xacro:property name="flexor_ii_metacarpals_tunnel_tf" value="0.021 -0.0015 0.051" />
    <xacro:property name="flexor_iii_metacarpals_tunnel_tf" value="0.007 0.0 0.051" />
    <xacro:property name="flexor_iv_metacarpals_tunnel_tf" value="-0.007 -0.005 0.051" />

    <xacro:property name="dorsal_interossei_ii_metacarpals_tunnel_tf" value="0.034 0.002 0.074" />
    <xacro:property name="palmar_interossei_ii_metacarpals_tunnel_tf" value="0.020 0.004 0.075" />
    <xacro:property name="dorsal_interossei_iii_metacarpals_tunnel_tf" value="0.015 0.002 0.077" />
    <xacro:property name="palmar_interossei_iii_metacarpals_tunnel_tf" value="0.002 0.002 0.077" />
    <xacro:property name="dorsal_interossei_iv_metacarpals_tunnel_tf" value="-0.0025 -0.003 0.076" />
    <xacro:property name="palmar_interossei_iv_metacarpals_tunnel_tf" value="-0.015 -0.004 0.075" />
    <xacro:property name="dorsal_interossei_v_metacarpals_tunnel_tf" value="0.006 -0.006 -0.013" />
    <xacro:property name="palmar_interossei_v_metacarpals_tunnel_tf" value="-0.006 -0.006 -0.013" />
    
    

    <xacro:property name="extensor_communis_ii_carpals_tunnel_tf" value="0.012 0.011 0.015" />
    <xacro:property name="extensor_communis_iii_carpals_tunnel_tf" value="0.004 0.011 0.015" />
    <xacro:property name="extensor_communis_iv_carpals_tunnel_tf" value="-0.004 0.011 0.015" />
    <xacro:property name="extensor_communis_v_carpals_tunnel_tf" value="-0.012 0.011 0.015" />

    <xacro:property name="flexor_ii_carpals_tunnel_tf" value="0.012 -0.011 0.012" />
    <xacro:property name="flexor_iii_carpals_tunnel_tf" value="0.004 -0.011 0.012" />
    <xacro:property name="flexor_iv_carpals_tunnel_tf" value="-0.004 -0.011 0.012" />
    <xacro:property name="flexor_v_carpals_tunnel_tf" value="-0.012 -0.011 0.012" />

    <xacro:property name="extensor_communis_ii_origin_tf" value="0.012 0.013 -0.035" />
    <xacro:property name="extensor_communis_iii_origin_tf" value="0.004 0.013 -0.035" />
    <xacro:property name="extensor_communis_iv_origin_tf" value="-0.004 0.013 -0.035" />
    <xacro:property name="extensor_communis_v_origin_tf" value="-0.012 0.013 -0.035" />
    
    <xacro:property name="flexor_profundus_ii_origin_tf" value="0.008 -0.013 -0.035" />
    <xacro:property name="flexor_profundus_iii_origin_tf" value="0.002 -0.013 -0.035" />
    <xacro:property name="flexor_profundus_iv_origin_tf" value="-0.002 -0.013 -0.035" />
    <xacro:property name="flexor_profundus_v_origin_tf" value="-0.008 -0.013 -0.035" /> 
    
    <xacro:property name="palmar_interossei_ii_origin_tf" value="0.010 -0.013 -0.045" />
    <xacro:property name="palmar_interossei_iii_origin_tf" value="0.003 -0.013 -0.045" />
    <xacro:property name="palmar_interossei_iv_origin_tf" value="-0.003 -0.013 -0.045" />
    <xacro:property name="palmar_interossei_v_origin_tf" value="-0.010 -0.013 -0.045" /> 

    <xacro:property name="dorsal_interossei_ii_origin_tf" value="0.010 -0.013 -0.055" />
    <xacro:property name="dorsal_interossei_iii_origin_tf" value="0.003 -0.013 -0.055" />
    <xacro:property name="dorsal_interossei_iv_origin_tf" value="-0.003 -0.013 -0.055" />
    <xacro:property name="dorsal_interossei_v_origin_tf" value="-0.010 -0.013 -0.055" />

    <xacro:property name="flexor_superficialis_ii_origin_tf" value="0.012 -0.013 -0.065" />
    <xacro:property name="flexor_superficialis_iii_origin_tf" value="0.004 -0.013 -0.065" />
    <xacro:property name="flexor_superficialis_iv_origin_tf" value="-0.004 -0.013 -0.065" />
    <xacro:property name="flexor_superficialis_v_origin_tf" value="-0.012 -0.013 -0.065" />
    
    <!-- Digit 1 Tendons -->
    <xacro:property name="abductor_pollicis_brevis_origin_tf" value="0.012 -0.013 -0.075" />
    <xacro:property name="abductor_pollicis_brevis_carpals_tunnel_tf" value="0.024963 -0.016395 0.022153" />
    <xacro:property name="abductor_pollicis_brevis_insertion_tf" value="0.008 0.0 0.0" />

    <xacro:property name="adductor_pollicis_origin_tf" value="0.0 -0.013 -0.085" />
    <xacro:property name="adductor_pollicis_metacarpals_iii_tunnel_i_tf" value="0.009064 -0.000907 0.041" />
    <xacro:property name="adductor_pollicis_metacarpals_iii_tunnel_ii_tf" value="0.011 0.001949 0.070" />
    <xacro:property name="adductor_pollicis_capitate_tunnel_tf" value="0.0 -0.010 0.016" />
    <xacro:property name="adductor_pollicis_insertion_tf" value="-0.008 0.0 0.0" />

    <xacro:property name="flexor_pollicis_brevis_origin_tf" value="0.004 -0.013 -0.075" />
    <xacro:property name="flexor_pollicis_brevis_carpals_tunnel_tf" value="0.0128 -0.00957 0.020" />
    <xacro:property name="flexor_pollicis_brevis_insertion_tf" value="0.005 -0.005598 0.008406" />

    <xacro:property name="opponens_pollicis_origin_tf" value="0.0 -0.013 -0.075" />
    <xacro:property name="opponens_pollicis_carpals_tunnel_tf" value="0.0128 -0.00957 0.020" />
    <xacro:property name="opponens_pollicis_insertion_i_tf" value="0.0055 0.0048 0.009875" />
    <xacro:property name="opponens_pollicis_insertion_ii_tf" value="0.00543 0.005595 0.03379" />

    <xacro:property name="flexor_pollicis_longus_origin_tf" value="0.008 -0.013 -0.075" />
    <xacro:property name="flexor_pollicis_longus_insertion_tf" value="0.0 -0.005 0.007" />

    <xacro:property name="extensor_pollicis_brevis_insertion_tf" value="0.0 0.006 0.008" />
    <xacro:property name="extensor_pollicis_brevis_origin_tf" value="0.012 0.013 -0.045" />

    <xacro:property name="extensor_pollicis_longus_insertion_tf" value="0.0 0.005 0.007" />
    <xacro:property name="extensor_pollicis_longus_origin_tf" value="0.004 0.013 -0.045" />
    <!-- brevis and longus tunnel -->
    <xacro:property name="extensor_pollicis_carpals_tunnel_tf" value="0.024 0.001 0.016" />


    <xacro:property name="abductor_pollicis_longus_origin_tf" value="0.012 0.013 -0.055" />
    <xacro:property name="abductor_pollicis_longus_insertion_tf" value="0.0055 0.0 0.008" />


    <xacro:property name="metacarpal_i_flexor_tunnel_tf" value="0.0 -0.0065 ${metacarpal_i_length/2}" />
    <xacro:property name="metacarpal_i_extensor_tunnel_tf" value="0.0 0.0065 ${metacarpal_i_length/2}" />
    <xacro:property name="pp_i_flexor_tunnel_tf" value="0.0 -0.005 ${pp_i_length/2}" />
    <xacro:property name="pp_i_extensor_tunnel_tf" value="0.0 0.005 ${pp_i_length/2}" />


    <!-- Digit V Tendons -->
    <xacro:property name="opponens_digiti_minimi_origin_tf" value="-0.012 -0.013 -0.075" />
    <xacro:property name="opponens_digiti_minimi_carpals_tunnel_tf" value="-0.007 -0.010 0.016" />
    <xacro:property name="opponens_digiti_minimi_insertion_i_tf" value="-0.0065 0.005506 -0.026175" />
    <xacro:property name="opponens_digiti_minimi_insertion_ii_tf" value="-0.0045 0.00665 -0.013738" />
    <xacro:property name="opponens_digiti_minimi_distal_cm_v_tunnel_tf" value="-0.0065 -0.0035 -0.007" />

    <!-- Carpal Tendons -->
    <xacro:property name="flexor_carpi_radialis_insertion_tf" value="0.02 -0.015 0.016" />
    <xacro:property name="flexor_carpi_ulnaris_insertion_tf" value="-0.0185 -0.012 0.016" />
    <xacro:property name="extensor_carpi_radialis_insertion_tf" value="0.021 0.01 0.016" />
    <xacro:property name="extensor_carpi_ulnaris_insertion_tf" value="-0.0185 0.012 0.016" />

    <xacro:property name="flexor_carpi_radialis_origin_tf" value="0.012 -0.013 -0.085" />
    <xacro:property name="flexor_carpi_ulnaris_origin_tf" value="-0.012 -0.013 -0.085" />
    <xacro:property name="extensor_carpi_radialis_origin_tf" value="0.012 0.013 -0.065" />
    <xacro:property name="extensor_carpi_ulnaris_origin_tf" value="-0.012 0.013 -0.065" />


    <!-- MOCAPS -->
    <xacro:property name="fingertip_target_mocap_size" value="0.004" />
    <xacro:property name="fingertip_target_mocap_rgba" value="1 0 0 1" />



    <!-- Tendon Origin Macro -->
    <xacro:macro name="tendon_origin" params="site_name site_tf">
        <site name="${site_name}" pos="${site_tf}" size="${origin_site_size}" rgba="${origin_site_rgba}"/>
    </xacro:macro>

    <!-- Fingertip Mocap Target -->
    <xacro:macro name="fingertip_target" params="hand_name name rgba:=${fingertip_target_mocap_rgba}">
        <body name="${hand_name}_${name}" pos="0 0.25 0" mocap="true" >
            <geom type="sphere" size="${fingertip_target_mocap_size}" rgba="${rgba}" />
            <geom type="cylinder" size="${fingertip_target_mocap_size/2} ${3*fingertip_target_mocap_size}" 
                    pos="0 0 ${1.5*fingertip_target_mocap_size}" rgba="${rgba}" />
        </body>
    </xacro:macro>
    
    <!-- DARM Hand -->
    <xacro:macro name="darm_hand" params="hand_name pos">
        <!-- NOTE: Only the required mocap bodies should be exposed -->
        <!-- DIGIT I Taget MOCAP -->
        <xacro:if value="$(arg digit_i)">
            <xacro:fingertip_target hand_name="${hand_name}" name="fingertip_i_target" rgba="1 0 0 1" />
        </xacro:if>

        <!-- DIGIT II Taget MOCAP -->
        <xacro:if value="$(arg digit_ii)">
            <xacro:fingertip_target hand_name="${hand_name}" name="fingertip_ii_target" rgba="0 1 0 1" />
        </xacro:if>

        <!-- DIGIT III Taget MOCAP -->
        <xacro:if value="$(arg digit_iii)">
            <xacro:fingertip_target hand_name="${hand_name}" name="fingertip_iii_target" rgba="0 0 1 1" />
        </xacro:if>

        <!-- DIGIT IV Taget MOCAP -->
        <xacro:if value="$(arg digit_iv)">
            <xacro:fingertip_target hand_name="${hand_name}" name="fingertip_iv_target" rgba="1 1 1 1" />
        </xacro:if>

        <!-- DIGIT V Taget MOCAP -->
        <xacro:if value="$(arg digit_v)">
            <xacro:fingertip_target hand_name="${hand_name}" name="fingertip_v_target" rgba="0.7 0.3 0 1" />
        </xacro:if>

        
        <body name="${hand_name}_forearm" pos="${pos}" euler="0 0 0" childclass="darm_meshes">
            <geom type="mesh" mesh="forearm_mesh" />
            
            <site name="${hand_name}_rc_joint_wrap_dorsal_sidesite" pos="0 ${rc_joint_radius+sidesite_size} ${rc_joint_tf[2]}" 
                size="${sidesite_size}" rgba="${sidesite_rgba}" />
            <site name="${hand_name}_rc_joint_wrap_palmar_sidesite" pos="0 -${rc_joint_radius+sidesite_size} ${rc_joint_tf[2]}" 
                size="${sidesite_size}" rgba="${sidesite_rgba}" />

            <xacro:tendon_origin site_name="${hand_name}_flexor_carpi_radialis_origin" site_tf="${flexor_carpi_radialis_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_carpi_ulnaris_origin" site_tf="${flexor_carpi_ulnaris_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_extensor_carpi_radialis_origin" site_tf="${extensor_carpi_radialis_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_extensor_carpi_ulnaris_origin" site_tf="${extensor_carpi_ulnaris_origin_tf}" />
            
            <xacro:tendon_origin site_name="${hand_name}_extensor_communis_ii_origin" site_tf="${extensor_communis_ii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_extensor_communis_iii_origin" site_tf="${extensor_communis_iii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_extensor_communis_iv_origin" site_tf="${extensor_communis_iv_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_extensor_communis_v_origin" site_tf="${extensor_communis_v_origin_tf}" />

            <xacro:tendon_origin site_name="${hand_name}_flexor_profundus_ii_origin" site_tf="${flexor_profundus_ii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_profundus_iii_origin" site_tf="${flexor_profundus_iii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_profundus_iv_origin" site_tf="${flexor_profundus_iv_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_profundus_v_origin" site_tf="${flexor_profundus_v_origin_tf}" />

            <xacro:tendon_origin site_name="${hand_name}_flexor_superficialis_ii_origin" site_tf="${flexor_superficialis_ii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_superficialis_iii_origin" site_tf="${flexor_superficialis_iii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_superficialis_iv_origin" site_tf="${flexor_superficialis_iv_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_superficialis_v_origin" site_tf="${flexor_superficialis_v_origin_tf}" />

            <xacro:tendon_origin site_name="${hand_name}_palmar_interossei_ii_origin" site_tf="${palmar_interossei_ii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_palmar_interossei_iii_origin" site_tf="${palmar_interossei_iii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_palmar_interossei_iv_origin" site_tf="${palmar_interossei_iv_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_palmar_interossei_v_origin" site_tf="${palmar_interossei_v_origin_tf}" />

            <xacro:tendon_origin site_name="${hand_name}_dorsal_interossei_ii_origin" site_tf="${dorsal_interossei_ii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_dorsal_interossei_iii_origin" site_tf="${dorsal_interossei_iii_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_dorsal_interossei_iv_origin" site_tf="${dorsal_interossei_iv_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_dorsal_interossei_v_origin" site_tf="${dorsal_interossei_v_origin_tf}" />

            <xacro:tendon_origin site_name="${hand_name}_flexor_pollicis_longus_origin" site_tf="${flexor_pollicis_longus_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_flexor_pollicis_brevis_origin" site_tf="${flexor_pollicis_brevis_origin_tf}" />
            
            <xacro:tendon_origin site_name="${hand_name}_extensor_pollicis_brevis_origin" site_tf="${extensor_pollicis_brevis_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_extensor_pollicis_longus_origin" site_tf="${extensor_pollicis_longus_origin_tf}" />
            
            <xacro:tendon_origin site_name="${hand_name}_abductor_pollicis_longus_origin" site_tf="${abductor_pollicis_longus_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_abductor_pollicis_brevis_origin" site_tf="${abductor_pollicis_brevis_origin_tf}" />
            
            <xacro:tendon_origin site_name="${hand_name}_opponens_pollicis_origin" site_tf="${opponens_pollicis_origin_tf}" />
            <xacro:tendon_origin site_name="${hand_name}_adductor_pollicis_origin" site_tf="${adductor_pollicis_origin_tf}" />
            
            <xacro:tendon_origin site_name="${hand_name}_opponens_digiti_minimi_origin" site_tf="${opponens_digiti_minimi_origin_tf}" />
            

            <!-- TODO: Measure this accurately from f360 -->
            <body name="${hand_name}_rc_centre_block" pos="${rc_joint_tf[0]} ${rc_joint_tf[1]} ${rc_joint_tf[2]}" euler="0 0 0">
                <xacro:unless value="$(arg no_wrist)">
                    <joint type="hinge" axis="0 1 0" pos="0 0 -0.032" limited="true" range="-20 10" />
                </xacro:unless>
                <geom type="mesh" mesh="rc_centre_block_mesh" />
                <geom class="wrap_geom" name="${hand_name}_rc_joint_wrap" type="cylinder"  
                    size="${rc_joint_radius} ${rc_joint_length}" euler="0 90 0" rgba="${wrap_rgba}" />

                <body name="${hand_name}_carpals_metacarpals" pos="0 0 0" euler="0 0 0">
                    <xacro:unless value="$(arg no_wrist)">
                        <joint type="hinge" axis="1 0 0" limited="true" range="-80 80" />
                    </xacro:unless>
                    <geom type="mesh" mesh="carpals_metacarpals_mesh" />
                    <geom class="wrap_geom" pos="${mcp_ii_translation}" name="${hand_name}_mcp_ii_wrap" type="cylinder" size="${mcp_ii_radius} ${mcp_ii_radius}" euler="0 90 0" rgba="${wrap_rgba}" />
                    <geom class="wrap_geom" pos="${mcp_iii_translation}" name="${hand_name}_mcp_iii_wrap" type="cylinder" size="${mcp_iii_radius} ${mcp_iii_radius}" euler="0 90 0" rgba="${wrap_rgba}" />
                    <geom class="wrap_geom" pos="${mcp_iv_translation}" name="${hand_name}_mcp_iv_wrap" type="cylinder" size="${mcp_iv_radius} ${mcp_iv_radius}" euler="0 90 0" rgba="${wrap_rgba}" />


                    <site name="${hand_name}_flexor_carpi_radialis_insertion" pos="${flexor_carpi_radialis_insertion_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_carpi_ulnaris_insertion" pos="${flexor_carpi_ulnaris_insertion_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_carpi_radialis_insertion" pos="${extensor_carpi_radialis_insertion_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_carpi_ulnaris_insertion" pos="${extensor_carpi_ulnaris_insertion_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                    <site name="${hand_name}_extensor_pollicis_carpals_tunnel" pos="${extensor_pollicis_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>


                    <site name="${hand_name}_extensor_communis_ii_carpals_tunnel" pos="${extensor_communis_ii_carpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_communis_iii_carpals_tunnel" pos="${extensor_communis_iii_carpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_communis_iv_carpals_tunnel" pos="${extensor_communis_iv_carpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_communis_v_carpals_tunnel" pos="${extensor_communis_v_carpals_tunnel_tf}" 
                            size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                    <site name="${hand_name}_extensor_communis_ii_metacarpals_tunnel" pos="${extensor_communis_ii_metacarpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_communis_iii_metacarpals_tunnel" pos="${extensor_communis_iii_metacarpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_extensor_communis_iv_metacarpals_tunnel" pos="${extensor_communis_iv_metacarpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                    <site name="${hand_name}_flexor_ii_metacarpals_tunnel" pos="${flexor_ii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_iii_metacarpals_tunnel" pos="${flexor_iii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_iv_metacarpals_tunnel" pos="${flexor_iv_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                    <site name="${hand_name}_dorsal_interossei_ii_metacarpals_tunnel" pos="${dorsal_interossei_ii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_palmar_interossei_ii_metacarpals_tunnel" pos="${palmar_interossei_ii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_dorsal_interossei_iii_metacarpals_tunnel" pos="${dorsal_interossei_iii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_palmar_interossei_iii_metacarpals_tunnel" pos="${palmar_interossei_iii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_dorsal_interossei_iv_metacarpals_tunnel" pos="${dorsal_interossei_iv_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_palmar_interossei_iv_metacarpals_tunnel" pos="${palmar_interossei_iv_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>


                    <site name="${hand_name}_flexor_ii_carpals_tunnel" pos="${flexor_ii_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_iii_carpals_tunnel" pos="${flexor_iii_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_iv_carpals_tunnel" pos="${flexor_iv_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_v_carpals_tunnel" pos="${flexor_v_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    
                    <site name="${hand_name}_abductor_pollicis_brevis_carpals_tunnel" pos="${abductor_pollicis_brevis_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_adductor_pollicis_metacarpals_iii_tunnel_i" pos="${adductor_pollicis_metacarpals_iii_tunnel_i_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_adductor_pollicis_metacarpals_iii_tunnel_ii" pos="${adductor_pollicis_metacarpals_iii_tunnel_ii_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_adductor_pollicis_capitate_tunnel" pos="${adductor_pollicis_capitate_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_flexor_pollicis_brevis_carpals_tunnel" pos="${flexor_pollicis_brevis_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                    <site name="${hand_name}_opponens_pollicis_carpals_tunnel" pos="${opponens_pollicis_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                    <site name="${hand_name}_proximal_cm_i_wrap_dorsal_sidesite" pos="${cm_i_translation[0]+1.2*proximal_cm_i_radius+sidesite_size} ${cm_i_translation[1]} ${cm_i_translation[2]}" size="${sidesite_size}" rgba="${sidesite_rgba}" />
                    <site name="${hand_name}_proximal_cm_i_wrap_palmar_sidesite" pos="${cm_i_translation[0]-1.2*proximal_cm_i_radius-sidesite_size} ${cm_i_translation[1]} ${cm_i_translation[2]}" size="${sidesite_size}" rgba="${sidesite_rgba}" />
                    
                    <site name="${hand_name}_opponens_digiti_minimi_carpals_tunnel" pos="${opponens_digiti_minimi_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}" />
                    
                    
                    <!-- Digits I -->
                    <xacro:if value="$(arg digit_i)">
                        <xacro:phalanx_i hand_name="${hand_name}" index="i" cm_translation="${cm_i_translation}" cm_rotation="${cm_i_rotation}" 
                                        centre_block_offset="${cm_i_centre_block_offset}" metacarpal_length="${metacarpal_i_length}" 
                                        pp_length="${pp_i_length}" dp_length="${dp_i_length}" proximal_cm_radius="${proximal_cm_i_radius}" 
                                        distal_cm_radius="${distal_cm_i_radius}" mcp_radius="${mcp_i_radius}" ip_radius="${ip_i_radius}"
                                        abductor_pollicis_brevis_insertion_tf="${abductor_pollicis_brevis_insertion_tf}"
                                        abductor_pollicis_longus_insertion_tf="${abductor_pollicis_longus_insertion_tf}"
                                        adductor_pollicis_insertion_tf="${adductor_pollicis_insertion_tf}"
                                        flexor_pollicis_brevis_insertion_tf="${flexor_pollicis_brevis_insertion_tf}"
                                        opponens_pollicis_insertion_i_tf="${opponens_pollicis_insertion_i_tf}"
                                        opponens_pollicis_insertion_ii_tf="${opponens_pollicis_insertion_ii_tf}"
                                        flexor_pollicis_longus_insertion_tf="${flexor_pollicis_longus_insertion_tf}"
                                        extensor_pollicis_brevis_insertion_tf="${extensor_pollicis_brevis_insertion_tf}"
                                        extensor_pollicis_longus_insertion_tf="${extensor_pollicis_longus_insertion_tf}"
                                        metacarpal_i_flexor_tunnel_tf="${metacarpal_i_flexor_tunnel_tf}" 
                                        metacarpal_i_extensor_tunnel_tf="${metacarpal_i_extensor_tunnel_tf}" 
                                        pp_i_flexor_tunnel_tf="${pp_i_flexor_tunnel_tf}"
                                        pp_i_extensor_tunnel_tf="${pp_i_extensor_tunnel_tf}" />
                    </xacro:if>

                    <!-- Digits II -->
                    <xacro:if value="$(arg digit_ii)">
                        <xacro:phalanges hand_name="${hand_name}" index="ii" mcp_translation="${mcp_ii_translation}" mcp_rotation="${mcp_ii_rotation}" 
                                    pp_length="${pp_ii_length}" mp_length="${mp_ii_length}" dp_length="${dp_ii_length}"
                                    mcp_radius="${mcp_ii_radius}" 
                                    pip_radius="${pip_ii_radius}" dip_radius="${dip_ii_radius}"
                                    dorsal_interossei_insertion_tf="${dorsal_interossei_ii_insertion_tf}"
                                    palmar_interossei_insertion_tf="${palmar_interossei_ii_insertion_tf}"
                                    pp_extensor_communis_insertion_tf="${pp_ii_extensor_communis_insertion_tf}"
                                    flexor_superficialis_insertion_tf="${flexor_superficialis_ii_insertion_tf}"
                                    mp_extensor_hood_insertion_tf="${mp_ii_extensor_hood_insertion_tf}"
                                    flexor_profundus_insertion_tf="${flexor_profundus_ii_insertion_tf}"
                                    dp_extensor_hood_insertion_tf="${dp_ii_extensor_hood_insertion_tf}" />
                    </xacro:if>

                    <!-- Digits III -->
                    <xacro:if value="$(arg digit_iii)">
                        <xacro:phalanges hand_name="${hand_name}" index="iii" mcp_translation="${mcp_iii_translation}" mcp_rotation="${mcp_iii_rotation}" 
                                        pp_length="${pp_iii_length}" mp_length="${mp_iii_length}" dp_length="${dp_iii_length}"
                                        mcp_radius="${mcp_iii_radius}" 
                                        pip_radius="${pip_iii_radius}" dip_radius="${dip_iii_radius}"
                                        dorsal_interossei_insertion_tf="${dorsal_interossei_iii_insertion_tf}"
                                        palmar_interossei_insertion_tf="${palmar_interossei_iii_insertion_tf}"
                                        pp_extensor_communis_insertion_tf="${pp_iii_extensor_communis_insertion_tf}"
                                        flexor_superficialis_insertion_tf="${flexor_superficialis_iii_insertion_tf}"
                                        mp_extensor_hood_insertion_tf="${mp_iii_extensor_hood_insertion_tf}"
                                        flexor_profundus_insertion_tf="${flexor_profundus_iii_insertion_tf}"
                                        dp_extensor_hood_insertion_tf="${dp_iii_extensor_hood_insertion_tf}" />
                    </xacro:if>

                    <!-- Digits IV -->
                    <xacro:if value="$(arg digit_iv)">
                        <xacro:phalanges hand_name="${hand_name}" index="iv" mcp_translation="${mcp_iv_translation}" mcp_rotation="${mcp_iv_rotation}" 
                                        pp_length="${pp_iv_length}" mp_length="${mp_iv_length}" dp_length="${dp_iv_length}"
                                        mcp_radius="${mcp_iv_radius}" 
                                        pip_radius="${pip_iv_radius}" dip_radius="${dip_iv_radius}"
                                        dorsal_interossei_insertion_tf="${dorsal_interossei_iv_insertion_tf}"
                                        palmar_interossei_insertion_tf="${palmar_interossei_iv_insertion_tf}"
                                        pp_extensor_communis_insertion_tf="${pp_iv_extensor_communis_insertion_tf}"
                                        flexor_superficialis_insertion_tf="${flexor_superficialis_iv_insertion_tf}"
                                        mp_extensor_hood_insertion_tf="${mp_iv_extensor_hood_insertion_tf}"
                                        flexor_profundus_insertion_tf="${flexor_profundus_iv_insertion_tf}"
                                        dp_extensor_hood_insertion_tf="${dp_iv_extensor_hood_insertion_tf}" />
                    </xacro:if>

                    <!-- Digits V -->
                    <xacro:if value="$(arg digit_v)">
                        <xacro:phalanx_v hand_name="${hand_name}" index="v" cm_translation="${cm_v_translation}" cm_rotation="${cm_v_rotation}" 
                                        centre_block_offset="${cm_v_centre_block_offset}" metacarpal_length="${metacarpal_v_length}" 
                                        mcp_translation="${mcp_v_translation}" mcp_rotation="${mcp_v_rotation}" pp_length="${pp_v_length}" 
                                        mp_length="${mp_v_length}" dp_length="${dp_v_length}" proximal_cm_radius="${proximal_cm_v_radius}" 
                                        distal_cm_radius="${distal_cm_v_radius}" mcp_radius="${mcp_v_radius}" 
                                        pip_radius="${pip_v_radius}" dip_radius="${dip_v_radius}" 
                                        dorsal_interossei_metacarpals_tunnel_tf="${dorsal_interossei_v_metacarpals_tunnel_tf}" 
                                        palmar_interossei_metacarpals_tunnel_tf="${palmar_interossei_v_metacarpals_tunnel_tf}" 
                                        dorsal_interossei_insertion_tf="${dorsal_interossei_v_insertion_tf}" 
                                        palmar_interossei_insertion_tf="${palmar_interossei_v_insertion_tf}" 
                                        pp_extensor_communis_insertion_tf="${pp_v_extensor_communis_insertion_tf}" 
                                        flexor_superficialis_insertion_tf="${flexor_superficialis_v_insertion_tf}" 
                                        mp_extensor_hood_insertion_tf="${mp_v_extensor_hood_insertion_tf}" 
                                        flexor_profundus_insertion_tf="${flexor_profundus_v_insertion_tf}" 
                                        dp_extensor_hood_insertion_tf="${dp_v_extensor_hood_insertion_tf}" 
                                        opponens_digiti_minimi_insertion_i_tf="${opponens_digiti_minimi_insertion_i_tf}" 
                                        opponens_digiti_minimi_insertion_ii_tf="${opponens_digiti_minimi_insertion_ii_tf}" 
                                        opponens_digiti_minimi_distal_cm_v_tunnel_tf="${opponens_digiti_minimi_distal_cm_v_tunnel_tf}" />
                    </xacro:if>

                </body>
            </body>
        </body>
    </xacro:macro>

    <xacro:darm_hand hand_name="hand1" pos="0 0 0.12" />
    <!-- <xacro:darm_hand hand_name="hand2" pos="0.5 0 0.12" /> -->
</worldbody>