<?xml version="1.0" encoding="UTF-8"?>
<worldbody xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:include filename="phalanges.xml.xacro" />

    <!-- Wrist -->
    <xacro:property name="rc_joint_tf" value="${[0, 0, 0.032]}" />
    <xacro:property name="rc_joint_radius" value="0.012" />
    <xacro:property name="rc_joint_length" value="0.0235" />

    <!-- Digit I -->
    <xacro:property name="cm_i_translation" value="0.0223607 -0.0073321 0.0254833" />
    <xacro:property name="cm_i_rotation" value="24 -15 -75" />
    <xacro:property name="cm_i_centre_block_offset" value="0 0 0.013" />
    <xacro:property name="metacarpal_i_length" value="0.0395" />
    
    <xacro:property name="pp_i_length" value="0.0335" />

    <!-- Digit II -->
    <xacro:property name="mcp_ii_translation" value="0.0293 0.0087 0.0908" />
    <xacro:property name="mcp_ii_rotation" value="0 5 -10" />
    <xacro:property name="pp_ii_length" value="0.0488" />
    <xacro:property name="mp_ii_length" value="0.0268" />

    <xacro:property name="mcp_ii_radius" value="0.0110" />
    <xacro:property name="pip_ii_radius" value="0.0065" />
    <xacro:property name="dip_ii_radius" value="0.0055" />
    <xacro:property name="dorsal_interossei_ii_insertion_tf" value="0.007 -0.007 0.012" />
    <xacro:property name="palmar_interossei_ii_insertion_tf" value="-0.007 -0.007 0.012" />
    <xacro:property name="pp_ii_extensor_communis_insertion_tf" value="0 0.009 0.012" />
    <xacro:property name="flexor_superficialis_ii_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_ii_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_ii_insertion_tf" value="0 -0.004 0.007" />
    <xacro:property name="dp_ii_extensor_hood_insertion_tf" value="0 0.004 0.007" />
    
    <!-- Digit III -->
    <xacro:property name="mcp_iii_translation" value="0.0082 0.0087 0.0933" />
    <xacro:property name="mcp_iii_rotation" value="0 0 0" />
    <xacro:property name="pp_iii_length" value="0.0520" />
    <xacro:property name="mp_iii_length" value="0.0335" />

    <xacro:property name="mcp_iii_radius" value="0.0110" />
    <xacro:property name="pip_iii_radius" value="0.0070" />
    <xacro:property name="dip_iii_radius" value="0.0060" />
    <xacro:property name="dorsal_interossei_iii_insertion_tf" value="0.007 -0.007 0.012" />
    <xacro:property name="palmar_interossei_iii_insertion_tf" value="-0.007 -0.007 0.012" />
    <xacro:property name="pp_iii_extensor_communis_insertion_tf" value="0 0.009 0.012" />
    <xacro:property name="flexor_superficialis_iii_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_iii_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_iii_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="dp_iii_extensor_hood_insertion_tf" value="0 0.005 0.007" />

    <!-- Digit IV -->
    <xacro:property name="mcp_iv_translation" value="-0.0103 0.0021 0.0889" />
    <xacro:property name="mcp_iv_rotation" value="0 -5 5" />
    <xacro:property name="pp_iv_length" value="0.0487" />
    <xacro:property name="mp_iv_length" value="0.0330" />

    <xacro:property name="mcp_iv_radius" value="0.0095" />
    <xacro:property name="pip_iv_radius" value="0.0065" />
    <xacro:property name="dip_iv_radius" value="0.0055" />
    <xacro:property name="dorsal_interossei_iv_insertion_tf" value="0.007 -0.007 0.012" />
    <xacro:property name="palmar_interossei_iv_insertion_tf" value="-0.007 -0.007 0.012" />
    <xacro:property name="pp_iv_extensor_communis_insertion_tf" value="0 0.007 0.012" />
    <xacro:property name="flexor_superficialis_iv_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_iv_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_iv_insertion_tf" value="0 -0.004 0.007" />
    <xacro:property name="dp_iv_extensor_hood_insertion_tf" value="0 0.004 0.007" />

    <!-- Digit V -->
    <xacro:property name="cm_v_translation" value="-0.0171 0.0038 0.0360" />
    <xacro:property name="cm_v_rotation" value="0 -12 5" />
    <xacro:property name="cm_v_centre_block_offset" value="0 0 0.014" />
    <xacro:property name="metacarpal_v_length" value="0.0349" />
    
    <xacro:property name="mcp_v_translation" value="0 0 0" />
    <xacro:property name="mcp_v_rotation" value="0 0 0" />
    <xacro:property name="pp_v_length" value="0.0416" />
    <xacro:property name="mp_v_length" value="0.0247" />

    <xacro:property name="mcp_v_radius" value="0.0095" />
    <xacro:property name="pip_v_radius" value="0.0060" />
    <xacro:property name="dip_v_radius" value="0.0050" />
    <xacro:property name="dorsal_interossei_v_insertion_tf" value="0.0055 -0.006 0.012" />
    <xacro:property name="palmar_interossei_v_insertion_tf" value="-0.0055 -0.006 0.012" />
    <xacro:property name="pp_v_extensor_communis_insertion_tf" value="0 0.0075 0.012" />
    <xacro:property name="flexor_superficialis_v_insertion_tf" value="0 -0.005 0.007" />
    <xacro:property name="mp_v_extensor_hood_insertion_tf" value="0 0.005 0.007" />
    <xacro:property name="flexor_profundus_v_insertion_tf" value="0 -0.004 0.007" />
    <xacro:property name="dp_v_extensor_hood_insertion_tf" value="0 0.004 0.007" />
    
    <!-- Tendons -->
    <xacro:property name="tunnel_site_size" value="0.0015" />
    <xacro:property name="tunnel_site_rgba" value="0.5 0.5 0.5 1" />
    <xacro:property name="origin_site_size" value="0.0015" />
    <xacro:property name="origin_site_rgba" value="1 0.5 0.5 1" />
    <xacro:property name="sidesite_size" value="0.001" />
    <xacro:property name="sidesite_rgba" value="1 1 1 0.2" />
    <xacro:property name="wrap_rgba" value="0 0 1 0.2" />
    
    <xacro:property name="extensor_communis_ii_metacarpals_tunnel_tf" value="0.021 0.013 0.051" />
    <xacro:property name="extensor_communis_iii_metacarpals_tunnel_tf" value="0.007 0.013 0.051" />
    <xacro:property name="extensor_communis_iv_metacarpals_tunnel_tf" value="-0.007 0.010 0.051" />

    <xacro:property name="flexor_ii_metacarpals_tunnel_tf" value="0.021 -0.0015 0.051" />
    <xacro:property name="flexor_iii_metacarpals_tunnel_tf" value="0.007 0.0 0.051" />
    <xacro:property name="flexor_iv_metacarpals_tunnel_tf" value="-0.007 -0.005 0.051" />

    <xacro:property name="extensor_communis_ii_carpals_tunnel_tf" value="0.012 0.011 0.015" />
    <xacro:property name="extensor_communis_iii_carpals_tunnel_tf" value="0.004 0.011 0.015" />
    <xacro:property name="extensor_communis_iv_carpals_tunnel_tf" value="-0.004 0.011 0.015" />
    <xacro:property name="extensor_communis_v_carpals_tunnel_tf" value="-0.012 0.011 0.015" />

    <xacro:property name="flexor_ii_carpals_tunnel_tf" value="0.012 -0.011 0.012" />
    <xacro:property name="flexor_iii_carpals_tunnel_tf" value="0.004 -0.011 0.012" />
    <xacro:property name="flexor_iv_carpals_tunnel_tf" value="-0.004 -0.011 0.012" />
    <xacro:property name="flexor_v_carpals_tunnel_tf" value="-0.012 -0.011 0.012" />

    <xacro:property name="extensor_communis_ii_origin_tf" value="0.012 0.013 -0.035" />
    <xacro:property name="extensor_communis_iii_origin_tf" value="0.004 0.013 -0.035" />
    <xacro:property name="extensor_communis_iv_origin_tf" value="-0.004 0.013 -0.035" />
    <xacro:property name="extensor_communis_v_origin_tf" value="-0.012 0.013 -0.035" />
    
    <xacro:property name="flexor_profundus_ii_origin_tf" value="0.008 -0.013 -0.035" />
    <xacro:property name="flexor_profundus_iii_origin_tf" value="0.002 -0.013 -0.035" />
    <xacro:property name="flexor_profundus_iv_origin_tf" value="-0.002 -0.013 -0.035" />
    <xacro:property name="flexor_profundus_v_origin_tf" value="-0.008 -0.013 -0.035" /> 
    
    <xacro:property name="palmar_interossei_ii_origin_tf" value="0.010 -0.013 -0.045" />
    <xacro:property name="palmar_interossei_iii_origin_tf" value="0.003 -0.013 -0.045" />
    <xacro:property name="palmar_interossei_iv_origin_tf" value="-0.003 -0.013 -0.045" />
    <xacro:property name="palmar_interossei_v_origin_tf" value="-0.010 -0.013 -0.045" /> 

    <xacro:property name="dorsal_interossei_ii_origin_tf" value="0.010 -0.013 -0.055" />
    <xacro:property name="dorsal_interossei_iii_origin_tf" value="0.003 -0.013 -0.055" />
    <xacro:property name="dorsal_interossei_iv_origin_tf" value="-0.003 -0.013 -0.055" />
    <xacro:property name="dorsal_interossei_v_origin_tf" value="-0.010 -0.013 -0.055" />

    <xacro:property name="flexor_superficialis_ii_origin_tf" value="0.012 -0.013 -0.075" />
    <xacro:property name="flexor_superficialis_iii_origin_tf" value="0.004 -0.013 -0.075" />
    <xacro:property name="flexor_superficialis_iv_origin_tf" value="-0.004 -0.013 -0.075" />
    <xacro:property name="flexor_superficialis_v_origin_tf" value="-0.012 -0.013 -0.075" />
    
    
    <xacro:property name="abductor_pollicis_brevis_origin_tf" value="0.0223607 -0.0073321 0.0254833" />
    

    <!-- Tendon Origin Macro -->
    <xacro:macro name="tendon_origin" params="site_name site_tf">
        <body>
            <site name="${site_name}" pos="${site_tf}" size="${origin_site_size}" rgba="${origin_site_rgba}"/>
        </body>
    </xacro:macro>
    
    

    <body name="forearm" pos="0 0 0.12" euler="0 0 0" childclass="darm_meshes">
        <geom type="mesh" mesh="forearm_mesh" />
        <geom name="rc_joint_wrap" type="cylinder" pos="${rc_joint_tf[0]} ${rc_joint_tf[1]} ${rc_joint_tf[2]}" 
            size="${rc_joint_radius} ${rc_joint_length}" euler="0 90 0" rgba="${wrap_rgba}" />
        
        <site name="rc_joint_wrap_dorsal_sidesite" pos="0 ${rc_joint_radius+sidesite_size} ${rc_joint_tf[2]}" 
            size="${sidesite_size}" rgba="${sidesite_rgba}" />
        <site name="rc_joint_wrap_palmar_sidesite" pos="0 -${rc_joint_radius+sidesite_size} ${rc_joint_tf[2]}" 
            size="${sidesite_size}" rgba="${sidesite_rgba}" />

        <xacro:tendon_origin site_name="extensor_communis_ii_origin" site_tf="${extensor_communis_ii_origin_tf}" />
        <xacro:tendon_origin site_name="extensor_communis_iii_origin" site_tf="${extensor_communis_iii_origin_tf}" />
        <xacro:tendon_origin site_name="extensor_communis_iv_origin" site_tf="${extensor_communis_iv_origin_tf}" />
        <xacro:tendon_origin site_name="extensor_communis_v_origin" site_tf="${extensor_communis_v_origin_tf}" />

        <xacro:tendon_origin site_name="flexor_profundus_ii_origin" site_tf="${flexor_profundus_ii_origin_tf}" />
        <xacro:tendon_origin site_name="flexor_profundus_iii_origin" site_tf="${flexor_profundus_iii_origin_tf}" />
        <xacro:tendon_origin site_name="flexor_profundus_iv_origin" site_tf="${flexor_profundus_iv_origin_tf}" />
        <xacro:tendon_origin site_name="flexor_profundus_v_origin" site_tf="${flexor_profundus_v_origin_tf}" />

        <xacro:tendon_origin site_name="flexor_superficialis_ii_origin" site_tf="${flexor_superficialis_ii_origin_tf}" />
        <xacro:tendon_origin site_name="flexor_superficialis_iii_origin" site_tf="${flexor_superficialis_iii_origin_tf}" />
        <xacro:tendon_origin site_name="flexor_superficialis_iv_origin" site_tf="${flexor_superficialis_iv_origin_tf}" />
        <xacro:tendon_origin site_name="flexor_superficialis_v_origin" site_tf="${flexor_superficialis_v_origin_tf}" />

        <xacro:tendon_origin site_name="palmar_interossei_ii_origin" site_tf="${palmar_interossei_ii_origin_tf}" />
        <xacro:tendon_origin site_name="palmar_interossei_iii_origin" site_tf="${palmar_interossei_iii_origin_tf}" />
        <xacro:tendon_origin site_name="palmar_interossei_iv_origin" site_tf="${palmar_interossei_iv_origin_tf}" />
        <xacro:tendon_origin site_name="palmar_interossei_v_origin" site_tf="${palmar_interossei_v_origin_tf}" />

        <xacro:tendon_origin site_name="dorsal_interossei_ii_origin" site_tf="${dorsal_interossei_ii_origin_tf}" />
        <xacro:tendon_origin site_name="dorsal_interossei_iii_origin" site_tf="${dorsal_interossei_iii_origin_tf}" />
        <xacro:tendon_origin site_name="dorsal_interossei_iv_origin" site_tf="${dorsal_interossei_iv_origin_tf}" />
        <xacro:tendon_origin site_name="dorsal_interossei_v_origin" site_tf="${dorsal_interossei_v_origin_tf}" />


        <!-- TODO: Measure this accurately from f360 -->
        <body name="rc_centre_block" pos="${rc_joint_tf[0]} ${rc_joint_tf[1]} ${rc_joint_tf[2]}" euler="0 0 0">
            <geom type="mesh" mesh="rc_centre_block_mesh" />

            <body name="carpals_metacarpals" pos="0 0 0" euler="0 0 0">
                <geom type="mesh" mesh="carpals_metacarpals_mesh" />

                <site name="extensor_communis_ii_carpals_tunnel" pos="${extensor_communis_ii_carpals_tunnel_tf}" 
                    size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="extensor_communis_iii_carpals_tunnel" pos="${extensor_communis_iii_carpals_tunnel_tf}" 
                    size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="extensor_communis_iv_carpals_tunnel" pos="${extensor_communis_iv_carpals_tunnel_tf}" 
                    size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="extensor_communis_v_carpals_tunnel" pos="${extensor_communis_v_carpals_tunnel_tf}" 
                        size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                <site name="extensor_communis_ii_metacarpals_tunnel" pos="${extensor_communis_ii_metacarpals_tunnel_tf}" 
                    size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="extensor_communis_iii_metacarpals_tunnel" pos="${extensor_communis_iii_metacarpals_tunnel_tf}" 
                    size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="extensor_communis_iv_metacarpals_tunnel" pos="${extensor_communis_iv_metacarpals_tunnel_tf}" 
                    size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                <site name="flexor_ii_metacarpals_tunnel" pos="${flexor_ii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="flexor_iii_metacarpals_tunnel" pos="${flexor_iii_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="flexor_iv_metacarpals_tunnel" pos="${flexor_iv_metacarpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                <site name="flexor_ii_carpals_tunnel" pos="${flexor_ii_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="flexor_iii_carpals_tunnel" pos="${flexor_iii_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="flexor_iv_carpals_tunnel" pos="${flexor_iv_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                <site name="flexor_v_carpals_tunnel" pos="${flexor_v_carpals_tunnel_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>
                
                <site name="abductor_pollicis_brevis_origin" pos="${abductor_pollicis_brevis_origin_tf}" size="${tunnel_site_size}" rgba="${tunnel_site_rgba}"/>

                
                <xacro:phalanges index="ii" mcp_translation="${mcp_ii_translation}" mcp_rotation="${mcp_ii_rotation}" 
                                pp_length="${pp_ii_length}" mp_length="${mp_ii_length}" mcp_radius="${mcp_ii_radius}" 
                                pip_radius="${pip_ii_radius}" dip_radius="${dip_ii_radius}"
                                dorsal_interossei_insertion_tf="${dorsal_interossei_ii_insertion_tf}"
                                palmar_interossei_insertion_tf="${palmar_interossei_ii_insertion_tf}"
                                pp_extensor_communis_insertion_tf="${pp_ii_extensor_communis_insertion_tf}"
                                flexor_superficialis_insertion_tf="${flexor_superficialis_ii_insertion_tf}"
                                mp_extensor_hood_insertion_tf="${mp_ii_extensor_hood_insertion_tf}"
                                flexor_profundus_insertion_tf="${flexor_profundus_ii_insertion_tf}"
                                dp_extensor_hood_insertion_tf="${dp_ii_extensor_hood_insertion_tf}" />

                <xacro:phalanges index="iii" mcp_translation="${mcp_iii_translation}" mcp_rotation="${mcp_iii_rotation}" 
                                pp_length="${pp_iii_length}" mp_length="${mp_iii_length}" mcp_radius="${mcp_iii_radius}" 
                                pip_radius="${pip_iii_radius}" dip_radius="${dip_iii_radius}"
                                dorsal_interossei_insertion_tf="${dorsal_interossei_iii_insertion_tf}"
                                palmar_interossei_insertion_tf="${palmar_interossei_iii_insertion_tf}"
                                pp_extensor_communis_insertion_tf="${pp_iii_extensor_communis_insertion_tf}"
                                flexor_superficialis_insertion_tf="${flexor_superficialis_iii_insertion_tf}"
                                mp_extensor_hood_insertion_tf="${mp_iii_extensor_hood_insertion_tf}"
                                flexor_profundus_insertion_tf="${flexor_profundus_iii_insertion_tf}"
                                dp_extensor_hood_insertion_tf="${dp_iii_extensor_hood_insertion_tf}" />

                <xacro:phalanges index="iv" mcp_translation="${mcp_iv_translation}" mcp_rotation="${mcp_iv_rotation}" 
                                pp_length="${pp_iv_length}" mp_length="${mp_iv_length}" mcp_radius="${mcp_iv_radius}" 
                                pip_radius="${pip_iv_radius}" dip_radius="${dip_iv_radius}"
                                dorsal_interossei_insertion_tf="${dorsal_interossei_iv_insertion_tf}"
                                palmar_interossei_insertion_tf="${palmar_interossei_iv_insertion_tf}"
                                pp_extensor_communis_insertion_tf="${pp_iv_extensor_communis_insertion_tf}"
                                flexor_superficialis_insertion_tf="${flexor_superficialis_iv_insertion_tf}"
                                mp_extensor_hood_insertion_tf="${mp_iv_extensor_hood_insertion_tf}"
                                flexor_profundus_insertion_tf="${flexor_profundus_iv_insertion_tf}"
                                dp_extensor_hood_insertion_tf="${dp_iv_extensor_hood_insertion_tf}" />

                <xacro:phalanx_v index="v" cm_translation="${cm_v_translation}" cm_rotation="${cm_v_rotation}" 
                                centre_block_offset="${cm_v_centre_block_offset}" metacarpal_length="${metacarpal_v_length}" 
                                mcp_translation="${mcp_v_translation}" mcp_rotation="${mcp_v_rotation}" pp_length="${pp_v_length}" 
                                mp_length="${mp_v_length}" mcp_radius="${mcp_v_radius}" 
                                pip_radius="${pip_v_radius}" dip_radius="${dip_v_radius}"
                                dorsal_interossei_insertion_tf="${dorsal_interossei_v_insertion_tf}"
                                palmar_interossei_insertion_tf="${palmar_interossei_v_insertion_tf}"
                                pp_extensor_communis_insertion_tf="${pp_v_extensor_communis_insertion_tf}"
                                flexor_superficialis_insertion_tf="${flexor_superficialis_v_insertion_tf}"
                                mp_extensor_hood_insertion_tf="${mp_v_extensor_hood_insertion_tf}"
                                flexor_profundus_insertion_tf="${flexor_profundus_v_insertion_tf}"
                                dp_extensor_hood_insertion_tf="${dp_v_extensor_hood_insertion_tf}" />
                
                <xacro:phalanx_i index="i" cm_translation="${cm_i_translation}" cm_rotation="${cm_i_rotation}" 
                                centre_block_offset="${cm_i_centre_block_offset}" metacarpal_length="${metacarpal_i_length}" 
                                pp_length="${pp_i_length}" />

                </body>
        </body>
    </body>
</worldbody>